In [28]:
# Import dependencies
import pandas as pd
import matplotlib.pyplot as plt

In [29]:
# Loading csv into pandas
data = pd.read_csv("data.csv")
data

,State or Territory,Industry division,Sex,Age group,4-Jan-20,11-Jan-20,18-Jan-20,25-Jan-20,1-Feb-20,8-Feb-20,...,4-Jul-20,11-Jul-20,18-Jul-20,25-Jul-20,1-Aug-20,8-Aug-20,15-Aug-20,22-Aug-20,29-Aug-20,5-Sep-20
0,0. Australia,0. All industries,0. Persons,0. All ages,92.8,95.2,96.7,97.5,98.0,98.7,...,96.3,96.5,96.4,96.4,96.5,96.2,96.1,95.9,95.6,95.5
1,0. Australia,0. All industries,0. Persons,1. Under 20,85.6,88.2,90.3,92.6,94.7,96.9,...,98.2,98.8,98.5,98.7,99.0,96.8,96.2,96.2,96.1,97.3
2,0. Australia,0. All industries,0. Persons,2. 20-29,91.3,94.1,96.1,97.1,97.5,98.1,...,93.5,94.0,93.9,93.9,94.0,93.9,93.7,93.6,93.3,93.3
3,0. Australia,0. All industries,0. Persons,3. 30-39,93.7,96.0,97.3,97.9,98.3,98.8,...,96.8,97.3,97.3,97.3,97.3,97.2,97.1,96.9,96.7,96.6
4,0. Australia,0. All industries,0. Persons,4. 40-49,93.8,95.9,97.1,97.8,98.3,98.9,...,97.5,98.0,97.9,98.1,98.1,98.0,97.9,97.8,97.5,97.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4322,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4323,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4324,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4325,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4326,NaN,NaN,NaN,NaN,NA = Not available,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
#data = data.dropna()
data['Age group'].unique()

array(['0. All ages', '1. Under 20', '2. 20-29', '3. 30-39', '4. 40-49',
       '5. 50-59', '6. 60-69', '7. 70 and over', nan], dtype=object)

In [31]:
# Renaming elements for easier referral in dataframe

# Removing integer in front of states
data["State or Territory"] = data["State or Territory"].replace({
    "0. Australia":"Australia",
    "1. NSW":"NSW",
    "2. VIC":"VIC",
    "3. QLD":"QLD",
    "4. SA":"SA",
    "5. WA":"WA",
    "6. TAS":"TAS",
    "7. NT":"NT",
    "8. ACT":"ACT"
})

# Removing integers in front of industries
data["Industry division"] = data["Industry division"].replace({
    "0. All industries":"All Industries",
    "01. A-Agriculture, forestry & fishing":"Agriculture, forestry & fishing",
    "02. B-Mining":"Mining",
    "03. C-Manufacturing":"Manufacturing",
    "04. D-Electricity, gas, water & waste services":"Electricity, gas, water & waste services",
    "05. E-Construction":"Construction",
    "06. F-Wholesale trade":"Wholesale trade",
    "07. G-Retail trade":"Retail trade",
    "08. H-Accommodation & food services":"Accommodation & food services",
    "09. I-Transport, postal & warehousing":"Transport, postal & warehousing",
    "10. J-Information media & telecommunications":"Information media & telecommunications",
    "11. K-Financial & insurance services":"Financial & insurance services",
    "12. L-Rental, hiring & real estate services":"Rental, hiring & real estate services",
    "13. M-Professional, scientific & technical services":"Professional, scientific & technical services",
    "14. N-Administrative & support services":"Administrative & support services",
    "15. O-Public administration & safety":"Public administration & safety",
    "16. P-Education & training":"Education & training",
    "17. Q-Health care & social assistance":"Health care & social assistance",
    "18. R-Arts & recreation services":"Arts & recreation services",
    "19. S-Other services":"Other services"  
})

# Removing integers in front of genders
data["Sex"] = data["Sex"].replace({
    "0. Persons":"Other",
    "1. Males":"Males",
    "2. Females":"Females"
})

# Removing integers in front of ages
data["Age group"] = data["Age group"].replace({
    "0. All ages":"All ages",
    "1. Under 20":"Under 20",
    "2. 20-29":"20-29",
    "3. 30-39":"30-39",
    "4. 40-49":"40-49",
    "5. 50-59":"50-59",
    "6. 60-69":"60-69",
    "7. 70 and over":"70 and over"
})

In [32]:
# Removing any nan values within the data frame
data = data.dropna()
data

,State or Territory,Industry division,Sex,Age group,4-Jan-20,11-Jan-20,18-Jan-20,25-Jan-20,1-Feb-20,8-Feb-20,...,4-Jul-20,11-Jul-20,18-Jul-20,25-Jul-20,1-Aug-20,8-Aug-20,15-Aug-20,22-Aug-20,29-Aug-20,5-Sep-20
0,Australia,All Industries,Other,All ages,92.8,95.2,96.7,97.5,98.0,98.7,...,96.3,96.5,96.4,96.4,96.5,96.2,96.1,95.9,95.6,95.5
1,Australia,All Industries,Other,Under 20,85.6,88.2,90.3,92.6,94.7,96.9,...,98.2,98.8,98.5,98.7,99.0,96.8,96.2,96.2,96.1,97.3
2,Australia,All Industries,Other,20-29,91.3,94.1,96.1,97.1,97.5,98.1,...,93.5,94.0,93.9,93.9,94.0,93.9,93.7,93.6,93.3,93.3
3,Australia,All Industries,Other,30-39,93.7,96.0,97.3,97.9,98.3,98.8,...,96.8,97.3,97.3,97.3,97.3,97.2,97.1,96.9,96.7,96.6
4,Australia,All Industries,Other,40-49,93.8,95.9,97.1,97.8,98.3,98.9,...,97.5,98.0,97.9,98.1,98.1,98.0,97.9,97.8,97.5,97.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4280,ACT,Arts & recreation services,Males,All ages,89.3,93.9,96.3,91.7,93.0,101.9,...,86.6,89.7,90.3,91.5,92.4,93.5,93.8,93.0,91.9,82.8
4288,ACT,Arts & recreation services,Females,All ages,85.8,91.8,95.7,94.7,96.2,103.6,...,84.7,89.5,91.2,93.5,94.9,95.8,96.5,96.7,96.6,91.9
4296,ACT,Other services,Other,All ages,94.7,96.8,99.0,99.2,99.2,100.9,...,100.6,101.9,102.1,102.4,101.5,101.4,101.6,101.4,101.3,101.1
4304,ACT,Other services,Males,All ages,97.2,99.6,101.8,101.9,101.8,102.8,...,101.0,103.6,104.3,104.6,103.3,102.5,102.6,102.0,102.4,101.9
4312,ACT,Other services,Females,All ages,93.6,95.2,97.7,97.9,97.9,99.7,...,99.2,99.6,99.5,99.8,99.2,99.7,100.0,99.9,99.2,98.9

In [33]:
# Checking all unique industry names
data["Industry division"].unique()

array(['All Industries', 'Agriculture, forestry & fishing', 'Mining',
       'Manufacturing', 'Electricity, gas, water & waste services',
       'Construction', 'Wholesale trade', 'Retail trade',
       'Accommodation & food services', 'Transport, postal & warehousing',
       'Information media & telecommunications',
       'Financial & insurance services',
       'Rental, hiring & real estate services',
       'Professional, scientific & technical services',
       'Administrative & support services',
       'Public administration & safety', 'Education & training',
       'Health care & social assistance', 'Arts & recreation services',
       'Other services'], dtype=object)

In [34]:
# Extracting data for Australia only from original dataframe
australia_df = data.loc[data['State or Territory'] == "VIC"]
australia_df

,State or Territory,Industry division,Sex,Age group,4-Jan-20,11-Jan-20,18-Jan-20,25-Jan-20,1-Feb-20,8-Feb-20,...,4-Jul-20,11-Jul-20,18-Jul-20,25-Jul-20,1-Aug-20,8-Aug-20,15-Aug-20,22-Aug-20,29-Aug-20,5-Sep-20
960,VIC,All Industries,Other,All ages,92.2,94.3,96.2,97.3,97.9,98.7,...,95.3,95.3,94.9,94.5,94.3,93.6,93.0,92.4,91.9,91.7
961,VIC,All Industries,Other,Under 20,83.5,85.6,89.0,91.9,94.9,96.9,...,94.8,93.7,91.1,89.3,87.8,82.8,80.2,79.7,78.8,79.5
962,VIC,All Industries,Other,20-29,90.8,93.1,95.5,96.8,97.3,98.2,...,92.1,92.0,91.3,90.5,90.2,89.5,88.7,88.0,87.6,87.4
963,VIC,All Industries,Other,30-39,93.2,95.3,97.0,97.8,98.1,98.7,...,96.4,96.8,96.6,96.2,96.0,95.7,95.3,94.7,94.3,94.1
964,VIC,All Industries,Other,40-49,93.2,94.9,96.4,97.4,98.0,98.7,...,96.9,97.3,97.4,97.2,97.2,96.8,96.5,95.9,95.5,95.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1400,VIC,Arts & recreation services,Males,All ages,95.5,97.4,99.7,100.8,100.8,99.8,...,84.3,85.3,84.6,83.9,82.6,80.2,81.4,80.6,80.8,80.3
1408,VIC,Arts & recreation services,Females,All ages,89.7,92.8,97.1,99.4,100.6,101.8,...,78.7,82.0,80.3,78.8,78.0,75.3,75.9,74.5,74.5,73.6
1416,VIC,Other services,Other,All ages,91.3,94.2,96.3,97.8,98.3,97.7,...,96.4,95.3,93.9,92.7,92.5,91.4,90.7,88.8,87.9,87.1
1424,VIC,Other services,Males,All ages,92.7,96.0,97.9,99.4,99.7,98.9,...,98.0,97.3,96.4,95.7,95.6,94.5,93.8,92.4,91.5,90.9
1432,VIC,Other services,Females,All ages,91.2,93.6,95.9,97.2,97.8,97.1,...,95.3,93.8,92.0,90.6,90.3,89.3,88.7,86.5,85.7,84.8

In [39]:
# Extracting data for all industries in Australia from original dataframe
australia_all_industries = australia_df.loc[australia_df["Industry division"] == "All Industries"]
australia_all_industries

,State or Territory,Industry division,Sex,Age group,4-Jan-20,11-Jan-20,18-Jan-20,25-Jan-20,1-Feb-20,8-Feb-20,...,11-Jul-20,18-Jul-20,25-Jul-20,1-Aug-20,8-Aug-20,15-Aug-20,22-Aug-20,29-Aug-20,5-Sep-20,Group
960,VIC,All Industries,Other,All Industries_Other_All ages,92.2,94.3,96.2,97.3,97.9,98.7,...,95.3,94.9,94.5,94.3,93.6,93.0,92.4,91.9,91.7,All Industries_Other_All ages
961,VIC,All Industries,Other,All Industries_Other_Under 20,83.5,85.6,89.0,91.9,94.9,96.9,...,93.7,91.1,89.3,87.8,82.8,80.2,79.7,78.8,79.5,All Industries_Other_Under 20
962,VIC,All Industries,Other,All Industries_Other_20-29,90.8,93.1,95.5,96.8,97.3,98.2,...,92.0,91.3,90.5,90.2,89.5,88.7,88.0,87.6,87.4,All Industries_Other_20-29
963,VIC,All Industries,Other,All Industries_Other_30-39,93.2,95.3,97.0,97.8,98.1,98.7,...,96.8,96.6,96.2,96.0,95.7,95.3,94.7,94.3,94.1,All Industries_Other_30-39
964,VIC,All Industries,Other,All Industries_Other_40-49,93.2,94.9,96.4,97.4,98.0,98.7,...,97.3,97.4,97.2,97.2,96.8,96.5,95.9,95.5,95.3,All Industries_Other_40-49
965,VIC,All Industries,Other,All Industries_Other_50-59,93.6,95.5,97.0,98.1,98.7,99.1,...,97.2,97.2,97.2,97.3,97.0,96.6,96.0,95.5,95.5,All Industries_Other_50-59
966,VIC,All Industries,Other,All Industries_Other_60-69,94.2,95.7,97.1,98.2,98.8,99.3,...,94.0,94.1,94.0,94.1,93.7,93.2,92.3,91.8,91.8,All Industries_Other_60-69
967,VIC,All Industries,Other,All Industries_Other_70 and over,91.7,92.6,94.5,96.0,97.5,98.7,...,88.2,88.1,87.7,87.7,86.6,86.0,84.9,84.3,83.9,All Industries_Other_70 and over
968,VIC,All Industries,Males,All Industries_Males_All ages,92.3,95.0,97.2,98.2,98.6,99.1,...,95.6,95.3,94.8,94.6,93.9,93.4,92.9,92.5,92.2,All Industries_Males_All ages
969,VIC,All Industries,Males,All Industries_Males_Under 20,85.7,88.0,91.7,94.1,96.7,98.7,...,93.2,91.2,89.7,88.3,84.0,81.7,81.3,80.8,81.5,All Industries_Males_Under 20
970,VIC,All Industries,Males,All Industries_Males_20-29,90.3,93.3,96.2,97.3,97.6,98.5,...,92.5,91.7,90.9,90.6,89.9,89.2,88.7,88.2,88.1,All Industries_Males_20-29
971,VIC,All Industries,Males,All Industries_Males_30-39,93.3,95.9,98.1,98.8,98.9,99.2,...,96.7,96.5,96.1,95.8,95.4,95.1,94.6,94.2,94.0,All Industries_Males_30-39
972,VIC,All Industries,Males,All Industries_Males_40-49,93.7,96.0,97.8,98.6,98.9,99.1,...,97.6,97.7,97.4,97.2,96.8,96.5,96.2,95.9,95.6,All Industries_Males_40-49
973,VIC,All Industries,Males,All Industries_Males_50-59,93.3,95.7,97.6,98.6,98.9,99.1,...,97.4,97.6,97.2,97.2,96.9,96.5,96.1,95.8,95.6,All Industries_Males_50-59
974,VIC,All Industries,Males,All Industries_Males_60-69,93.4,95.5,97.4,98.4,98.9,99.4,...,94.4,94.7,94.3,94.4,93.9,93.5,92.9,92.5,92.3,All Industries_Males_60-69
975,VIC,All Industries,Males,All Industries_Males_70 and over,90.8,92.1,94.4,95.9,97.3,98.7,...,89.1,89.4,88.7,88.8,87.4,87.1,86.2,85.6,85.5,All Industries_Males_70 and over
976,VIC,All Industries,Females,All Industries_Females_All ages,93.2,94.5,95.9,97.1,97.9,98.7,...,95.0,94.7,94.3,94.2,93.6,93.0,92.1,91.6,91.4,All Industries_Females_All ages
977,VIC,All Industries,Females,All Industries_Females_Under 20,88.2,89.5,92.3,94.8,97.7,99.3,...,89.1,86.0,84.1,82.4,77.9,75.5,74.9,73.7,73.9,All Industries_Females_Under 20
978,VIC,All Industries,Females,All Industries_Females_20-29,92.7,94.2,96.1,97.4,97.9,98.7,...,92.0,91.5,90.6,90.3,89.5,88.7,88.0,87.5,87.2,All Industries_Females_20-29
979,VIC,All Industries,Females,All Industries_Females_30-39,93.9,95.1,96.4,97.2,97.7,98.4,...,96.9,96.7,96.2,96.1,95.8,95.4,94.7,94.3,94.1,All Industries_Females_30-39
980,VIC,All Industries,Females,All Industries_Females_40-49,93,94.1,95.2,96.3,97.3,98.4,...,97.1,97.1,97.1,97.2,96.9,96.4,95.7,95.2,95.1,All Industries_Females_40-49
981,VIC,All Industries,Females,All Industries_Females_50-59,94,95.4,96.6,97.7,98.6,99.1,...,96.9,96.9,97.1,97.4,97.2,96.7,95.8,95.3,95.3,All Industries_Females_50-59
982,VIC,All Industries,Females,All Industries_Females_60-69,95.1,95.8,96.8,98.0,98.8,99.2,...,93.6,93.5,93.7,93.8,93.5,92.8,91.7,91.1,91.2,All Industries_Females_60-69
983,VIC,All Industries,Females,All Industries_Females_70 and over,93,93.3,94.6,96.0,97.5,98.5,...,86.9,86.2,86.2,86.2,85.2,84.4,83.1,82.5,81.9,All Industries_Females_70 and over

In [40]:
# Combining industry division, gender and age group into a single group column
australia_df["Group"] = australia_df["Industry division"] + "_" + australia_df["Sex"] + "_" + australia_df["Age group"]

<ipython-input-40-a9cbca689a85>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  australia_df["Group"] = australia_df["Industry division"] + "_" + australia_df["Sex"] + "_" + australia_df["Age group"]

In [41]:
# Replacing the age group with combined groups
australia_df["Age group"] = australia_df["Group"]

<ipython-input-41-679f9491fa96>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  australia_df["Age group"] = australia_df["Group"]

In [12]:
australia_df

,State or Territory,Industry division,Sex,Age group,4-Jan-20,11-Jan-20,18-Jan-20,25-Jan-20,1-Feb-20,8-Feb-20,...,11-Jul-20,18-Jul-20,25-Jul-20,1-Aug-20,8-Aug-20,15-Aug-20,22-Aug-20,29-Aug-20,5-Sep-20,Group
0,Australia,All Industries,Other,All Industries_Other_All ages,92.8,95.2,96.7,97.5,98.0,98.7,...,96.5,96.4,96.4,96.5,96.2,96.1,95.9,95.6,95.5,All Industries_Other_All ages
1,Australia,All Industries,Other,All Industries_Other_Under 20,85.6,88.2,90.3,92.6,94.7,96.9,...,98.8,98.5,98.7,99.0,96.8,96.2,96.2,96.1,97.3,All Industries_Other_Under 20
2,Australia,All Industries,Other,All Industries_Other_20-29,91.3,94.1,96.1,97.1,97.5,98.1,...,94.0,93.9,93.9,94.0,93.9,93.7,93.6,93.3,93.3,All Industries_Other_20-29
3,Australia,All Industries,Other,All Industries_Other_30-39,93.7,96.0,97.3,97.9,98.3,98.8,...,97.3,97.3,97.3,97.3,97.2,97.1,96.9,96.7,96.6,All Industries_Other_30-39
4,Australia,All Industries,Other,All Industries_Other_40-49,93.8,95.9,97.1,97.8,98.3,98.9,...,98.0,97.9,98.1,98.1,98.0,97.9,97.8,97.5,97.5,All Industries_Other_40-49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
461,Australia,Other services,Other,Other services_Other_50-59,92.7,95.4,97.1,98.4,99.1,98.8,...,99.0,98.7,99.0,98.9,98.8,98.7,97.8,97.4,97.6,Other services_Other_50-59
462,Australia,Other services,Other,Other services_Other_60-69,93.8,96.4,98.1,99.1,99.7,99.6,...,97.7,97.5,97.5,97.2,97.2,96.9,95.8,95.6,95.8,Other services_Other_60-69
463,Australia,Other services,Other,Other services_Other_70 and over,93.3,95.4,97.1,98.2,99.3,98.3,...,95.0,94.6,94.8,94.6,92.9,91.7,90.3,90.1,89.5,Other services_Other_70 and over
464,Australia,Other services,Males,Other services_Males_All ages,92.8,96.4,98.4,99.1,99.4,99.0,...,98.0,97.7,97.6,97.2,96.8,96.6,95.8,95.3,94.9,Other services_Males_All ages
472,Australia,Other services,Females,Other services_Females_All ages,91.2,94.0,95.8,97.0,97.9,98.3,...,95.8,95.4,95.7,95.2,94.9,94.6,93.9,93.5,93.3,Other services_Females_All ages

In [13]:
# Removing individual unwanted columns
del australia_df["State or Territory"]

In [14]:
del australia_df["Industry division"]

In [15]:
del australia_df["Sex"]

In [16]:
del australia_df["Group"]

In [17]:
australia_df = australia_df.rename(columns={
    "Age group":"Group"
})

In [18]:
australia_df

,Group,4-Jan-20,11-Jan-20,18-Jan-20,25-Jan-20,1-Feb-20,8-Feb-20,15-Feb-20,22-Feb-20,29-Feb-20,...,4-Jul-20,11-Jul-20,18-Jul-20,25-Jul-20,1-Aug-20,8-Aug-20,15-Aug-20,22-Aug-20,29-Aug-20,5-Sep-20
0,All Industries_Other_All ages,92.8,95.2,96.7,97.5,98.0,98.7,99.2,99.3,99.3,...,96.3,96.5,96.4,96.4,96.5,96.2,96.1,95.9,95.6,95.5
1,All Industries_Other_Under 20,85.6,88.2,90.3,92.6,94.7,96.9,98.2,96.9,96.0,...,98.2,98.8,98.5,98.7,99.0,96.8,96.2,96.2,96.1,97.3
2,All Industries_Other_20-29,91.3,94.1,96.1,97.1,97.5,98.1,98.7,99.0,99.1,...,93.5,94.0,93.9,93.9,94.0,93.9,93.7,93.6,93.3,93.3
3,All Industries_Other_30-39,93.7,96.0,97.3,97.9,98.3,98.8,99.3,99.4,99.5,...,96.8,97.3,97.3,97.3,97.3,97.2,97.1,96.9,96.7,96.6
4,All Industries_Other_40-49,93.8,95.9,97.1,97.8,98.3,98.9,99.3,99.4,99.4,...,97.5,98.0,97.9,98.1,98.1,98.0,97.9,97.8,97.5,97.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
461,Other services_Other_50-59,92.7,95.4,97.1,98.4,99.1,98.8,99.1,99.6,100.2,...,98.9,99.0,98.7,99.0,98.9,98.8,98.7,97.8,97.4,97.6
462,Other services_Other_60-69,93.8,96.4,98.1,99.1,99.7,99.6,99.6,99.8,100.3,...,97.9,97.7,97.5,97.5,97.2,97.2,96.9,95.8,95.6,95.8
463,Other services_Other_70 and over,93.3,95.4,97.1,98.2,99.3,98.3,97.8,97.8,97.9,...,95.4,95.0,94.6,94.8,94.6,92.9,91.7,90.3,90.1,89.5
464,Other services_Males_All ages,92.8,96.4,98.4,99.1,99.4,99.0,99.3,99.5,100.2,...,98.3,98.0,97.7,97.6,97.2,96.8,96.6,95.8,95.3,94.9
472,Other services_Females_All ages,91.2,94.0,95.8,97.0,97.9,98.3,98.9,99.5,100.2,...,96.5,95.8,95.4,95.7,95.2,94.9,94.6,93.9,93.5,93.3

In [19]:
# Checking transposed data
australia_df.T.head()

,0,1,2,3,4,5,6,7,8,9,...,456,457,458,459,460,461,462,463,464,472
Group,All Industries_Other_All ages,All Industries_Other_Under 20,All Industries_Other_20-29,All Industries_Other_30-39,All Industries_Other_40-49,All Industries_Other_50-59,All Industries_Other_60-69,All Industries_Other_70 and over,All Industries_Males_All ages,All Industries_Males_Under 20,...,Other services_Other_All ages,Other services_Other_Under 20,Other services_Other_20-29,Other services_Other_30-39,Other services_Other_40-49,Other services_Other_50-59,Other services_Other_60-69,Other services_Other_70 and over,Other services_Males_All ages,Other services_Females_All ages
4-Jan-20,92.8,85.6,91.3,93.7,93.8,94.2,94.3,91.2,92.9,87.4,...,91.4,75.1,90.8,93,92.3,92.7,93.8,93.3,92.8,91.2
11-Jan-20,95.2,88.2,94.1,96,95.9,96.4,96.4,93.2,96,90.5,...,94.7,83.2,94.6,96,94.8,95.4,96.4,95.4,96.4,94
18-Jan-20,96.7,90.3,96.1,97.3,97.1,97.7,97.5,94.2,97.7,92.7,...,96.7,88.4,96.8,97.6,96.4,97.1,98.1,97.1,98.4,95.8
25-Jan-20,97.5,92.6,97.1,97.9,97.8,98.3,98.2,95.7,98.4,94.6,...,97.7,91.3,97.3,98.6,97.7,98.4,99.1,98.2,99.1,97

In [20]:
# Creating a transposed dataframe of Australia data
australia_df_t = australia_df.T

In [21]:
# Cleaning transposed dataframe
# Grabing the first row for the header
new_header = australia_df_t.iloc[0]

# Taking the data less the header row
australia_df_t = australia_df_t[1:] 

# Setting the header row as the df header
australia_df_t.columns = new_header

In [22]:
australia_df_t.head()

Group,All Industries_Other_All ages,All Industries_Other_Under 20,All Industries_Other_20-29,All Industries_Other_30-39,All Industries_Other_40-49,All Industries_Other_50-59,All Industries_Other_60-69,All Industries_Other_70 and over,All Industries_Males_All ages,All Industries_Males_Under 20,...,Other services_Other_All ages,Other services_Other_Under 20,Other services_Other_20-29,Other services_Other_30-39,Other services_Other_40-49,Other services_Other_50-59,Other services_Other_60-69,Other services_Other_70 and over,Other services_Males_All ages,Other services_Females_All ages
4-Jan-20,92.8,85.6,91.3,93.7,93.8,94.2,94.3,91.2,92.9,87.4,...,91.4,75.1,90.8,93,92.3,92.7,93.8,93.3,92.8,91.2
11-Jan-20,95.2,88.2,94.1,96,95.9,96.4,96.4,93.2,96,90.5,...,94.7,83.2,94.6,96,94.8,95.4,96.4,95.4,96.4,94
18-Jan-20,96.7,90.3,96.1,97.3,97.1,97.7,97.5,94.2,97.7,92.7,...,96.7,88.4,96.8,97.6,96.4,97.1,98.1,97.1,98.4,95.8
25-Jan-20,97.5,92.6,97.1,97.9,97.8,98.3,98.2,95.7,98.4,94.6,...,97.7,91.3,97.3,98.6,97.7,98.4,99.1,98.2,99.1,97
1-Feb-20,98,94.7,97.5,98.3,98.3,98.7,98.7,97.1,98.6,96.5,...,98.3,93.4,97.8,98.7,98.6,99.1,99.7,99.3,99.4,97.9

In [23]:
# Filtering by elements check
australia_df_t.columns.str.contains("Male") & australia_df_t.columns.str.contains("Female")

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [47]:
# Filtering data by elements, replace a and b with desired elements
# add & australia_df_t.columns.str.contains(c) for additional filtering
a = "All Industries"
b = "Other"
other= australia_df_t.loc[:, (australia_df_t.columns.str.contains(a) & australia_df_t.columns.str.contains(b))]
other

Group,All Industries_Other_All ages,All Industries_Other_Under 20,All Industries_Other_20-29,All Industries_Other_30-39,All Industries_Other_40-49,All Industries_Other_50-59,All Industries_Other_60-69,All Industries_Other_70 and over
4-Jan-20,92.8,85.6,91.3,93.7,93.8,94.2,94.3,91.2
11-Jan-20,95.2,88.2,94.1,96,95.9,96.4,96.4,93.2
18-Jan-20,96.7,90.3,96.1,97.3,97.1,97.7,97.5,94.2
25-Jan-20,97.5,92.6,97.1,97.9,97.8,98.3,98.2,95.7
1-Feb-20,98,94.7,97.5,98.3,98.3,98.7,98.7,97.1
8-Feb-20,98.7,96.9,98.1,98.8,98.9,99.2,99.3,98.5
15-Feb-20,99.2,98.2,98.7,99.3,99.3,99.5,99.6,99.5
22-Feb-20,99.3,96.9,99,99.4,99.4,99.4,99.6,99.6
29-Feb-20,99.3,96,99.1,99.5,99.4,99.4,99.5,99.3
7-Mar-20,99.8,99.1,99.8,99.8,99.8,99.8,100,100.2
14-Mar-20,100,100,100,100,100,100,100,100
21-Mar-20,99.3,98.2,99,99.4,99.5,99.5,99.3,99.1
28-Mar-20,96.3,89.4,93.9,97.1,97.8,97.8,97.3,95.9
4-Apr-20,93.7,81.7,89.3,95.2,96.3,96.4,95.3,92
11-Apr-20,91.9,77.2,86.7,93.9,95.2,95.4,93.7,88.7
18-Apr-20,91.5,77.1,86,93.5,94.8,95,93,87.4
25-Apr-20,91.8,77.9,86.5,93.7,95.1,95.3,93.3,87.7
2-May-20,92.2,79.8,86.8,93.9,95.4,95.7,93.8,88.6
9-May-20,92.7,81.3,87.7,94.3,95.8,96.1,94.4,89.6
16-May-20,93.3,82.4,88.3,94.7,96.2,96.5,94.9,91.6
23-May-20,93.6,83.3,88.9,94.9,96.4,96.7,95.1,92.1
30-May-20,94.1,85.7,89.6,95.3,96.7,96.9,95.4,92.5
6-Jun-20,95,88.8,91,96.1,97.3,97.4,95.9,93.6
13-Jun-20,95.5,90.2,91.6,96.6,97.7,97.8,96.1,92.9
20-Jun-20,95.7,92.9,92.2,96.5,97.5,97.6,95.9,92.9
27-Jun-20,95.6,95.6,92.4,96.1,97,97.1,95.4,92.7
4-Jul-20,96.3,98.2,93.5,96.8,97.5,97.5,95.7,92.6
11-Jul-20,96.5,98.8,94,97.3,98,97.8,95.3,91.1
18-Jul-20,96.4,98.5,93.9,97.3,97.9,97.8,95,90.4
25-Jul-20,96.4,98.7,93.9,97.3,98.1,97.9,95.1,90.5
1-Aug-20,96.5,99,94,97.3,98.1,98,95.1,90.6
8-Aug-20,96.2,96.8,93.9,97.2,98,97.9,94.9,89.9
15-Aug-20,96.1,96.2,93.7,97.1,97.9,97.8,94.7,89.8
22-Aug-20,95.9,96.2,93.6,96.9,97.8,97.6,94.4,89.5
29-Aug-20,95.6,96.1,93.3,96.7,97.5,97.3,94.2,89.3
5-Sep-20,95.5,97.3,93.3,96.6,97.5,97.4,94.2,88.9

In [48]:
a = "All Industries"
b = "Male"
male= australia_df_t.loc[:, (australia_df_t.columns.str.contains(a) & australia_df_t.columns.str.contains(b))]
male

Group,All Industries_Males_All ages,All Industries_Males_Under 20,All Industries_Males_20-29,All Industries_Males_30-39,All Industries_Males_40-49,All Industries_Males_50-59,All Industries_Males_60-69,All Industries_Males_70 and over
4-Jan-20,92.9,87.4,90.7,94,94.3,94.1,93.5,90.5
11-Jan-20,96,90.5,94.4,96.8,96.9,96.8,96.3,92.6
18-Jan-20,97.7,92.7,96.7,98.4,98.2,98.2,97.7,94
25-Jan-20,98.4,94.6,97.6,98.9,98.8,98.7,98.4,95.5
1-Feb-20,98.6,96.5,97.9,99,98.9,98.9,98.8,97
8-Feb-20,99.1,98.5,98.5,99.2,99.2,99.3,99.4,98.5
15-Feb-20,99.4,99.7,99,99.5,99.5,99.5,99.5,99.3
22-Feb-20,99.5,98.4,99.2,99.6,99.5,99.5,99.5,99.6
29-Feb-20,99.4,97.4,99.2,99.5,99.4,99.4,99.4,99.3
7-Mar-20,99.9,99.8,99.9,99.9,99.9,99.9,100,100.1
14-Mar-20,100,100,100,100,100,100,100,100
21-Mar-20,99.4,98.7,99.1,99.5,99.5,99.5,99.3,99
28-Mar-20,97,92.4,94.8,97.5,98.1,98.1,97.5,95.9
4-Apr-20,95.1,87.1,91.3,96.1,97.1,97.2,95.9,92.4
11-Apr-20,93.8,83.5,89,95.1,96.3,96.4,94.6,89.4
18-Apr-20,93.5,83.5,88.6,94.8,96.1,96.2,94.1,88.1
25-Apr-20,93.7,84.3,89,94.9,96.2,96.2,94.2,88.5
2-May-20,93.9,85.6,89.2,94.9,96.3,96.4,94.6,89.6
9-May-20,94.2,86.8,89.8,95.2,96.5,96.7,95.1,90.4
16-May-20,94.6,87.3,90.4,95.5,96.8,97,95.5,91.7
23-May-20,94.7,87.6,90.5,95.5,96.8,97,95.6,92.2
30-May-20,95,89.2,91.1,95.7,96.9,97.1,95.7,92.4
6-Jun-20,95.6,90.9,92.2,96.2,97.3,97.5,96.1,93.5
13-Jun-20,95.8,91.3,92.3,96.5,97.6,97.8,96.4,93.3
20-Jun-20,95.7,93.3,92.7,96.1,97.1,97.3,95.8,93.4
27-Jun-20,95.1,95.2,92.5,95.3,96.1,96.2,94.8,92.9
4-Jul-20,95.8,97.3,93.6,96,96.8,96.9,95.2,92.7
11-Jul-20,96.3,97.2,94.2,96.9,97.7,97.7,95.3,91.4
18-Jul-20,96.2,96.6,93.9,96.9,97.7,97.7,95.1,90.8
25-Jul-20,96.2,96.5,93.9,96.9,97.8,97.9,95.2,91
1-Aug-20,96.1,96.5,93.9,96.7,97.7,97.8,95.1,91.1
8-Aug-20,95.8,94.3,93.8,96.5,97.5,97.6,94.9,90.3
15-Aug-20,95.6,93.5,93.5,96.4,97.4,97.5,94.8,90.1
22-Aug-20,95.5,93.4,93.6,96.3,97.3,97.4,94.6,89.8
29-Aug-20,95.1,93,93.2,96,97,97.1,94.2,89.7
5-Sep-20,95,94,93.3,95.8,96.8,97,94.1,89.3

In [ ]:
a = "All Industries"
b = "female"
male= australia_df_t.loc[:, (australia_df_t.columns.str.contains(a) & australia_df_t.columns.str.contains(b))]
male

In [ ]:
# Export file as a CSV, without the Pandas index, but with the header
file_one_df.to_csv("vic_all_industries.csv", index=False, header=True)